# Generated by Django 4.2.6 on 2023-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UdyanSaathiAPI', '0004_graphdatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutionmodel',
            name='Date',
            field=models.DateTimeField(default='2023-10-10 23:00:00'),
        ),
    ]
