# Generated by Django 4.2.6 on 2023-11-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UdyanSaathiAPI', '0006_aqicalendarmodel_topmetrocitiesmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphdatamodel',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='pollutionmodel',
            name='Date',
        ),
    ]
