# Generated by Django 4.2.6 on 2023-12-16 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UdyanSaathiAPI', '0007_remove_graphdatamodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdatamodel',
            name='Date',
            field=models.DateField(default='2023-10-10'),
        ),
        migrations.AddField(
            model_name='pollutionmodel',
            name='Date',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 10, 23, 0)),
        ),
    ]
