# Generated by Django 4.2.6 on 2023-12-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UdyanSaathiAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqicalendarmodel',
            name='Pol_Date',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='graphdatamodel',
            name='Pol_Date',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
